# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.srcs/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1.xci
# IP: The module: 'wolfenstein_platform_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.srcs/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1.xci
# IP: The module: 'wolfenstein_platform_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amrit/Documents/GitHub/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
