# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.srcs/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0.xci
# IP: The module: 'audio_hw_platform_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.gen/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_hw_platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.gen/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_hw_platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.gen/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_hw_platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.srcs/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0.xci
# IP: The module: 'audio_hw_platform_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.gen/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_hw_platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.gen/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_hw_platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/audio_hw/audio_hw.gen/sources_1/bd/audio_hw_platform/ip/audio_hw_platform_axi_gpio_0_0/audio_hw_platform_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_hw_platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
