# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ensc452/zedboard_master.xdc

# Block Designs: bd/wolfenstein_platform/wolfenstein_platform.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wolfenstein_platform || ORIG_REF_NAME==wolfenstein_platform} -quiet] -quiet

# IP: bd/wolfenstein_platform/ip/wolfenstein_platform_processing_system7_0_0/wolfenstein_platform_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wolfenstein_platform_processing_system7_0_0 || ORIG_REF_NAME==wolfenstein_platform_processing_system7_0_0} -quiet] -quiet

# IP: bd/wolfenstein_platform/ip/wolfenstein_platform_vga_controller_0_0/wolfenstein_platform_vga_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wolfenstein_platform_vga_controller_0_0 || ORIG_REF_NAME==wolfenstein_platform_vga_controller_0_0} -quiet] -quiet

# IP: bd/wolfenstein_platform/ip/wolfenstein_platform_clk_wiz_0_0/wolfenstein_platform_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wolfenstein_platform_clk_wiz_0_0 || ORIG_REF_NAME==wolfenstein_platform_clk_wiz_0_0} -quiet] -quiet

# IP: bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_0/wolfenstein_platform_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wolfenstein_platform_proc_sys_reset_0_0 || ORIG_REF_NAME==wolfenstein_platform_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/wolfenstein_platform/ip/wolfenstein_platform_proc_sys_reset_0_1/wolfenstein_platform_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wolfenstein_platform_proc_sys_reset_0_1 || ORIG_REF_NAME==wolfenstein_platform_proc_sys_reset_0_1} -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/wolfenstein_platform_ooc.xdc
