# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Ian/Projects/school/ensc452/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.srcs/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_auto_pc_0_1/wolfenstein_platform_auto_pc_0.xci
# IP: The module: 'wolfenstein_platform_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ian/Projects/school/ensc452/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_auto_pc_0/wolfenstein_platform_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Ian/Projects/school/ensc452/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.srcs/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_auto_pc_0_1/wolfenstein_platform_auto_pc_0.xci
# IP: The module: 'wolfenstein_platform_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ian/Projects/school/ensc452/wolfenstein_clone/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_auto_pc_0/wolfenstein_platform_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wolfenstein_platform_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
