# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.srcs/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_vga_controller_0_0/wolfenstein_platform_vga_controller_0_0.xci
# IP: The module: 'wolfenstein_platform_vga_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.srcs/sources_1/bd/wolfenstein_platform/ip/wolfenstein_platform_vga_controller_0_0/wolfenstein_platform_vga_controller_0_0.xci
# IP: The module: 'wolfenstein_platform_vga_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Ian/Projects/school/ensc452/wolfenstein_platform/wolfenstein_platform.gen/sources_1/bd/wolfenstein_platform/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
